theme: jekyll-theme-minimal
title: Pagina Web para aprender
description: pronto sabre como llamarla por ahoa solo dire que la

licencia TintoWare, es que que por la cual si le resulta útil a alguien y lo utiliza se verá obligado, en caso de que se cruce en el camino del autor, a pagarse un vinito tinto pinchito incluido ;-)
